apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: online-shop-tls
  namespace: default
spec:
  secretName: online-shop-tls

  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer

  dnsNames:
    - app.yogifoods.store
